<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
<script src="../../html/js.js"></script>

<?php
$user = $this->user;
?>

Список пользователей:
<br><br>

<?php if ($users = $this->users): ?>
    <?php foreach ($users as $user): ?>
        <div id="user_block_<?= $user->getId(); ?>">
            id: <?= $user->getId(); ?>
            имя: <input type="text" id="name<?= $user->getId(); ?>"
                        value="<?= htmlspecialchars($user->getName()); ?>">
            email: <input type="text" id="email<?= $user->getId(); ?>"
                          value="<?= htmlspecialchars($user->email); ?>">
            пароль: <input type="text" id="password<?= $user->getId(); ?>">
            <br>
            <input type="button" onclick="saveUser(<?= $user->getId(); ?>);" value="Сохранить">
            <input type="button" onclick="deleteUser(<?= $user->getId(); ?>);" value="Удалить">

            <div id="resp_<?= $user->getId(); ?>">
            </div>
        </div>
    <?php endforeach; ?>
<?php else: ?>
    Сообщений пока нет
<?php endif; ?>

<script>
    function saveUser(userId) {
        $.post(
            '/admin/saveUser',
            {
                id: userId,
                name: $('#name' + userId).val(),
                email: $('#email_' + userId).val(),
                password: $('#password' + userId).val(),
            },
        );
    }

    function deleteUser(userId) {
        $.post(
            '/admin/deleteUser',
            {
                id: userId,
            },
        );
    }

    function addUser() {
        $.post(
            '/admin/addUser',
            {
                name: $('#user_name').val(),
                email: $('#user_email').val(),
                password: $('#user_password').val(),
            }
        );
    }
</script>

Добавить пользователя

name: <input type="text" id="user_name"> <br>
email: <input type="text" id="user_email"> <br>
password: <input type="text" id="user_password">
<input type="button" value="Отправить" onclick="addUser();">
<div id="resp">

</div>
