<?php
$user = $this->user;
?>

Вы вошли как <?= $user->getName(); ?>#<?= $user->getId(); ?> <a href="register/logout">выйти</a>
<br><br>

Сообщения:
<br>
<?php $user = $this->user;
if ($messages = $this->messages):
    foreach ($messages as $message):
        if ($user->isAdmin()): ?>
            <a href="/admin/deleteMessage/?id=<?= $message->getId(); ?>">Удалить</a>
        <?php endif; ?>
        <span><?= $message->getCreatedDate(); ?></span>
        <?php if ($author = $message->getAuthor()): ?>
        <span><?= htmlspecialchars($author->getName()); ?></span>
    <?php else: ?>
        <span>Сообщение от удаленного пользователя</span>
    <?php endif; ?>
        <div><?= htmlspecialchars(nl2br($message->getText())); ?></div>
        <?php if ($message->getImage()): ?>
        <div><img src="/images/<?= $message->getImage(); ?>"></div>
    <?php endif; ?>
    <?php endforeach; ?>
<?php else: ?>
    Нет изображений
<?php endif; ?>

<form enctype="multipart/form-data" action="/blog/addMessage" method="post">
    <textarea type="text" value="" name="text"></textarea><br><br>
    Добавить изображение: <input type="file" name="image"><br>
    <input type="submit" value="Отправить">
</form>